// Title screen, the prologue, and Petitioner selection.

import { CLASSES } from '../data/classes.js';
import { getItem } from '../data/items.js';
import { iconSvg } from './icons.js';
import { escapeHtml } from './hud.js';
import * as Audio from '../engine/audio.js';
import { GameState } from '../game/state.js';

export class TitleScreen {
  constructor(root, actions) {
    this.actions = actions;
    this.el = document.createElement('div');
    this.el.className = 'title-screen show';
    root.appendChild(this.el);
    this.stage = 'menu';
    this.selected = CLASSES[0].id;
    this.render();
  }

  show() { this.el.classList.add('show'); }
  hide() { this.el.classList.remove('show'); }

  render() {
    if (this.stage === 'menu') this.renderMenu();
    else if (this.stage === 'prologue') this.renderPrologue();
    else if (this.stage === 'class') this.renderClass();
    else if (this.stage === 'about') this.renderAbout();
  }

  renderMenu() {
    const save = GameState.peek();
    this.el.innerHTML = `
      <div class="ts-bg"><canvas id="ts-canvas"></canvas></div>
      <div class="ts-inner">
        <div class="ts-mark">${iconSvg('hex', 64)}</div>
        <h1 class="ts-title">THE VERROW</h1>
        <div class="ts-tag">A tower driven point-down into the salt, and ten questions on the way to the bottom.</div>
        <div class="ts-menu">
          ${save ? `<button data-a="continue" class="primary">
              Continue — Floor ${save.floorIndex}
              <span>${escapeHtml(clsName(save.classId))} · ${save.hearts}♥ · ${save.gold} gold</span>
            </button>` : ''}
          <button data-a="new" class="${save ? '' : 'primary'}">${save ? 'Begin a new descent' : 'Descend'}</button>
          <button data-a="settings">Settings</button>
          <button data-a="about">About the Verrow</button>
        </div>
        <div class="ts-foot">Built with three.js. Every texture, sound and figure in this game is generated by code.</div>
      </div>`;
    this.wire();
    this.startBackdrop();
  }

  renderPrologue() {
    this.el.innerHTML = `
      <div class="ts-bg"><canvas id="ts-canvas"></canvas></div>
      <div class="ts-inner narrow">
        <div class="prologue">
          <p>Two hundred years ago the world began to forget itself.</p>
          <p>Not gently, and not all at once. Names peeled off things first. Then roads forgot where they went. Then people forgot the faces of people they loved, and after that, that there had been a face at all. Whole provinces have gone quiet — still inhabited, still working, by people who can no longer say what they are doing or why, and who do not find this strange.</p>
          <p>They call it the Thinning.</p>
          <p>In the salt flats of Caudmere there is a black hexagonal plinth the size of a cathedral, and beneath it, driven point-down into the earth, a tower called <b>the Verrow</b>. It was once the Cadence: an engine-cathedral that measured and circulated the world’s remembering, the way a heart circulates blood. Ten floors. Ten functions. Ten Wards.</p>
          <p>Then it stopped. Or broke. Or chose. Nobody above ground knows which.</p>
          <p>Once a generation the plinth opens and one person may go down. They are called Petitioners. They are told three things, and then the salt closes over them.</p>
          <ol class="prologue-three">
            <li>There are ten floors. The tenth holds the Cadence itself.</li>
            <li>You have three heartbeats of grace.</li>
            <li>Nothing in the Verrow will lie to you. This is not a kindness.</li>
          </ol>
        </div>
        <div class="ts-menu row">
          <button data-a="back">Back</button>
          <button data-a="toclass" class="primary">Who is going down?</button>
        </div>
      </div>`;
    this.wire();
    this.startBackdrop();
  }

  renderClass() {
    const cls = CLASSES.find((c) => c.id === this.selected) || CLASSES[0];
    this.el.innerHTML = `
      <div class="ts-bg"><canvas id="ts-canvas"></canvas></div>
      <div class="ts-inner wide">
        <h2 class="ts-h2">Choose your Petitioner</h2>
        <p class="ts-note">Your calling changes which doors will open for you, and what people are willing to say. Every floor can be finished by any Petitioner — but not by the same route.</p>
        <div class="class-picker">
          <div class="class-list">
            ${CLASSES.map((c) => `
              <button class="class-tab ${c.id === this.selected ? 'on' : ''}" data-c="${c.id}" style="--c:${c.color}">
                <b>${escapeHtml(c.name)}</b><span>${escapeHtml(c.epithet)}</span>
              </button>`).join('')}
          </div>
          <div class="class-detail" style="--c:${cls.color};--c2:${cls.accent}">
            <h3>${escapeHtml(cls.name)} <em>${escapeHtml(cls.epithet)}</em></h3>
            <p class="class-blurb">${escapeHtml(cls.blurb)}</p>
            <h4>You can</h4>
            <ul>${cls.abilities.map((a) => `<li>${escapeHtml(a)}</li>`).join('')}</ul>
            <h4>You carry</h4>
            <div class="class-kit">
              <div class="kit-item gold">${iconSvg('coin', 24)}<div><b>${cls.gold} gold</b><span>starting purse</span></div></div>
              ${cls.items.map((id) => {
                const d = getItem(id);
                return `<div class="kit-item" style="--tint:${d.tint}">${iconSvg(d.icon, 24)}<div><b>${escapeHtml(d.name)}</b><span>${escapeHtml(d.desc)}</span></div></div>`;
              }).join('')}
            </div>
          </div>
        </div>
        <div class="ts-menu row">
          <button data-a="back">Back</button>
          <button data-a="begin" class="primary">Descend as the ${escapeHtml(cls.name)}</button>
        </div>
      </div>`;
    this.el.querySelectorAll('.class-tab').forEach((b) => {
      b.addEventListener('click', () => {
        this.selected = b.dataset.c;
        Audio.play('ui');
        this.renderClass();
      });
    });
    this.wire();
    this.startBackdrop();
  }

  renderAbout() {
    this.el.innerHTML = `
      <div class="ts-bg"><canvas id="ts-canvas"></canvas></div>
      <div class="ts-inner narrow">
        <h2 class="ts-h2">About</h2>
        <div class="prologue">
          <p><b>The Verrow</b> is a first-person dungeon with no combat in it anywhere. You walk, you talk, and you choose. Choices open doors, close others, cost you gold, items, or one of your three heartbeats of grace.</p>
          <p>Ten floors, each its own dungeon, each a branching story that fans out wide and comes back to one stair. Some branches are dead ends and will take a heart from you — but every dead end is telegraphed by someone, somewhere, if you were listening. Lose all three heartbeats and the tower keeps you.</p>
          <p>Finishing a floor by its hardest and most demanding route earns a <b>Ward Token</b>. There are ten. What they are for becomes clear at the bottom.</p>
          <h3>Controls</h3>
          <p class="keyline">
            <kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> move &nbsp;·&nbsp; <kbd>Mouse</kbd> look &nbsp;·&nbsp;
            <kbd>Shift</kbd> hurry &nbsp;·&nbsp; <kbd>E</kbd> speak &nbsp;·&nbsp; <kbd>Tab</kbd> satchel &nbsp;·&nbsp;
            <kbd>Esc</kbd> pause &nbsp;·&nbsp; <kbd>F3</kbd> performance
          </p>
          <h3>Under the hood</h3>
          <p>There are no asset files in this project. Every surface texture and its normal map is generated pixel by pixel at load; every figure, prop and room is assembled from primitives; every sound — the drones, the thunder, the footsteps, the voices — is synthesised in the Web Audio graph as you hear it. The dungeon layouts are solved from the authored room graphs, not generated: the same story always builds the same tower.</p>
        </div>
        <div class="ts-menu row"><button data-a="back" class="primary">Back</button></div>
      </div>`;
    this.wire();
    this.startBackdrop();
  }

  wire() {
    this.el.querySelectorAll('[data-a]').forEach((b) => {
      b.addEventListener('click', () => {
        Audio.resume();
        Audio.play('uiBig');
        const a = b.dataset.a;
        if (a === 'new') { this.stage = 'prologue'; this.render(); }
        else if (a === 'toclass') { this.stage = 'class'; this.render(); }
        else if (a === 'about') { this.stage = 'about'; this.render(); }
        else if (a === 'back') {
          this.stage = this.stage === 'class' ? 'prologue' : 'menu';
          this.render();
        }
        else if (a === 'begin') this.actions.begin(this.selected);
        else if (a === 'continue') this.actions.continue();
        else if (a === 'settings') this.actions.settings();
      });
    });
  }

  // A slow drifting field of motes behind the menu, so the title isn't static.
  startBackdrop() {
    const canvas = this.el.querySelector('#ts-canvas');
    if (!canvas) return;
    cancelAnimationFrame(this._raf);
    const ctx = canvas.getContext('2d');
    const dots = [];
    const resize = () => {
      canvas.width = canvas.clientWidth;
      canvas.height = canvas.clientHeight;
    };
    resize();
    this._resize = resize;
    window.addEventListener('resize', resize);
    for (let i = 0; i < 90; i++) {
      dots.push({
        x: Math.random(), y: Math.random(),
        r: 0.4 + Math.random() * 1.8,
        s: 0.006 + Math.random() * 0.02,
        a: 0.1 + Math.random() * 0.45
      });
    }
    const draw = () => {
      const w = canvas.width, h = canvas.height;
      ctx.clearRect(0, 0, w, h);
      const g = ctx.createRadialGradient(w / 2, h * 0.55, 0, w / 2, h * 0.55, Math.max(w, h) * 0.75);
      g.addColorStop(0, 'rgba(30,44,54,0.55)');
      g.addColorStop(1, 'rgba(4,6,10,0)');
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, w, h);
      for (const d of dots) {
        d.y -= d.s / 60;
        if (d.y < -0.02) { d.y = 1.02; d.x = Math.random(); }
        ctx.beginPath();
        ctx.arc(d.x * w, d.y * h, d.r, 0, 7);
        ctx.fillStyle = `rgba(190,224,236,${d.a})`;
        ctx.fill();
      }
      this._raf = requestAnimationFrame(draw);
    };
    draw();
  }

  stopBackdrop() {
    cancelAnimationFrame(this._raf);
    if (this._resize) window.removeEventListener('resize', this._resize);
  }
}

function clsName(id) {
  const c = CLASSES.find((x) => x.id === id);
  return c ? c.name : 'Petitioner';
}
